printWidth: 100
semi: true
singleQuote: true
trailingComma: es5
bracketSpacing: true
arrowParens: always
endOfLine: lf
useTabs: false
tabWidth: 2
jsxSingleQuote: false
bracketSameLine: false
plugins:
  - prettier-plugin-tailwindcss
